"""Initial Migration

Revision ID: 54144ef52ad5
Revises: 455c63b5b524
Create Date: 2021-06-23 10:16:45.016316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54144ef52ad5'
down_revision = '455c63b5b524'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('comment_at', sa.DateTime(), nullable=True),
    sa.Column('comment_by', sa.String(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    # ### end Alembic commands ###
